name: Integration and Unit Tests

on:
  workflow_call:
    secrets:
      GH_COMPOSER_AUTH:
        required: true

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  COMPOSER_AUTH: ${{ secrets.GH_COMPOSER_AUTH }}

jobs:
  testing:
    name: WP ${{ matrix.wordpress-version }} + PHP ${{ matrix.php-version }} + MS ${{ matrix.is-multisite }} + Allowed to fail ${{ matrix.allow-failure }}

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mariadb:11.2
        ports:
          - '3306:3306'
        env:
          MYSQL_ROOT_PASSWORD: wordpress
          MARIADB_INITDB_SKIP_TZINFO: 1
          MYSQL_USER: wordpress
          MYSQL_PASSWORD: wordpress
          MYSQL_DATABASE: wordpress_test

    strategy:
      fail-fast: false
      matrix:
        include:
          - wordpress-version: '6.2.x'
            php-version: '7.4'
            is-multisite: 0
            allow-failure: false
          - wordpress-version: 'latest'
            php-version: '7.2'
            is-multisite: 0
            allow-failure: false
          - wordpress-version: 'latest'
            php-version: '8.3'
            is-multisite: 0
            allow-failure: false
          - wordpress-version: 'latest'
            php-version: '8.0'
            is-multisite: 1
            allow-failure: false
          - wordpress-version: 'nightly'
            php-version: '7.2'
            is-multisite: 0
            allow-failure: true
          - wordpress-version: 'nightly'
            php-version: '8.4'
            is-multisite: 0
            allow-failure: true

    env:
      WP_MULTISITE: ${{ matrix.is-multisite }}

    steps:
      - name: Check out the source code
        uses: actions/checkout@v4

      - name: Run PHPUnit tests
        uses: polylang/actions/phpunit@main
        with:
          php-version: ${{ matrix.php-version }}
          wordpress-version: ${{ matrix.wordpress-version }}

      - name: Run Behat tests
        run: |
          PHP_DEPENDENCIES=$(composer show -D)
          if [[ $PHP_DEPENDENCIES == *"behat/behat"* ]]; then
          	echo "Behat is installed, let's run the tests."
          	vendor/bin/behat
          else
          	echo "Behat is not installed"
          	exit 0
          fi
